### ISSUE TITLE
Application fails to start since today

### ISSUE THREAD

**Issue by wouterhummelink** [spring-projects/spring-petclinic#307]
I'm using this application as a demoapp for build pipelines... since today the tests fail and spring-boot:run fails as well with the following root exception

 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: The configuration of the pool is sealed once started.  Use HikariConfigMXBean for runtime changes.

**Comment by arey** [comment]
I've got the same error.

**Comment by arey** [comment]
@dsyer  to avoid this kind of problem, maybe we could move to a Spring Boot Release Candidate instead of a SNAPSHOT?

**Comment by dsyer** [comment]
I want to track snapshots. That way we detect changes upstream quicker. This one should be fixed now (and in RC2), but it nearly wasn’t, and we detected the issue here.

**Comment by arey** [comment]
I confirm; petclinic is working again. Thanks Dave

**Comment by banank1989** [comment]
How to resolve this issue? Using spring 2.0.2.RELEASE and hikari 2.7.6? Still getting Caused by: java.lang.IllegalStateException: The configuration of the pool is sealed once started.  Use HikariConfigMXBean for runtime changes. erron refresh endpoint

**Comment by dsyer** [comment]
Please do not cross post (https://github.com/spring-cloud/spring-cloud-commons/issues/318#issuecomment-407177184).
